defmodule Tunez.Repo.Migrations.AddGinIndexForArtistNameSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE INDEX IF NOT EXISTS artists_name_trgm_index
    ON artists USING GIN (name gin_trgm_ops);
    """)
  end

  def down do
    execute("DROP INDEX IF EXISTS artists_name_trgm_index;")
  end
end
